# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ba810ff06cba71c405cb45adb009f695526a621660b1563989078d635371fa2b6b1e05096321b3ffdd18290611d02608cdddb07f290289678561d4bb3f2b389

test:
  secret_key_base: 7ecccf8511b02a5ad99718b014d58c8a297ef46e29188edc747bc1628f7832478ee77b91a36b02a2d00d25681202deb6f0a02f7885774fe02ff536ad7f5e6cdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
